include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    depend_on_referenced_packages: ignore
